/**
 * Shell-only labels (the PWA around the coach's views), with curated Dutch and Arabic. Kept out of
 * `presentation.ts` so the isolated-view kit bundle doesn't carry them; other languages are generated (see
 * `setLabelPack`).
 */
export const shellLabels: Record<string, [string, string]> = {
  "Chat model": ["Chatmodel", "نموذج المحادثة"],
  "Deep work model": ["Model voor diep werk", "نموذج العمل المتعمق"],
  "Talks with you: replies, check-ins, quick changes. Speed matters here.": ["Praat met je: antwoorden, check-ins, snelle aanpassingen. Hier telt snelheid.", "يتحدث معك: الردود والمتابعات والتعديلات السريعة. السرعة مهمة هنا."],
  "Works in the background on plans, reviews and research, where thinking matters more than speed.": ["Werkt op de achtergrond aan schema's, controles en onderzoek, waar nadenken belangrijker is dan snelheid.", "يعمل في الخلفية على الخطط والمراجعات والبحث، حيث التفكير أهم من السرعة."],
  "Your coach runs on AI models through OpenRouter. This shows who pays, what has been used and which models coach you.": ["Je coach draait op AI-modellen via OpenRouter. Hier zie je wie betaalt, wat er is gebruikt en welke modellen je coachen.", "يعمل مدربك بنماذج ذكاء اصطناعي عبر OpenRouter. يعرض هذا من يدفع وما تم استخدامه وأي النماذج تدربك."],
  "Plans built from your own training, for any sport": ["Plannen op basis van je eigen training, voor elke sport", "خطط مبنية على تدريبك أنت، لأي رياضة"],
  "A coach that checks in, adapts and remembers": ["Een coach die bijhoudt, bijstuurt en onthoudt", "مدرب يتابعك ويتكيّف ويتذكّر"],
  "Your data stays on this server, and you can export or delete it": ["Je gegevens blijven op deze server en je kunt ze exporteren of verwijderen", "تبقى بياناتك على هذا الخادم، ويمكنك تصديرها أو حذفها"],
  "Your AI coach, in your pocket": ["Je AI-coach, altijd bij je", "مدربك الذكي، في جيبك"],
  "Tell it what you train and what you want. It plans with you, keeps an eye on how it goes and adjusts, in your language.": ["Vertel wat je traint en wat je wilt. Je coach plant met je mee, houdt in de gaten hoe het gaat en stuurt bij, in jouw taal.", "أخبره بما تتدرّب عليه وما تريده. يخطط معك ويتابع تقدّمك ويعدّل الخطة، بلغتك."],
  "Please check the form.": ["Controleer het formulier.", "يرجى مراجعة النموذج."],
  "Join with your invite": ["Doe mee met je uitnodiging", "انضم عبر دعوتك"],
  "Set up your coach": ["Stel je coach in", "أعدّ مدربك"],
  "A few details and your coach is ready.": ["Nog een paar gegevens en je coach is klaar.", "بعض التفاصيل ويصبح مدربك جاهزًا."],
  "You are creating the first account, which administers this server.": ["Je maakt het eerste account aan; dat beheert deze server.", "أنت تنشئ الحساب الأول، وهو الذي يدير هذا الخادم."],
  "Invite code": ["Uitnodigingscode", "رمز الدعوة"],
  "Setup code": ["Installatiecode", "رمز الإعداد"],
  "From the person who invited you. It works once, for 24 hours.": ["Van degene die je heeft uitgenodigd. Werkt één keer, 24 uur lang.", "من الشخص الذي دعاك. يعمل مرة واحدة خلال 24 ساعة."],
  "From the server's first-run output.": ["Uit de uitvoer van de server bij de eerste start.", "من مخرجات التشغيل الأول للخادم."],
  "Change": ["Wijzigen", "تغيير"],
  "Name your coach": ["Geef je coach een naam", "سمِّ مدربك"],
  "You can change it later.": ["Je kunt dit later wijzigen.", "يمكنك تغييره لاحقًا."],
  "Before we start": ["Voordat we beginnen", "قبل أن نبدأ"],
  "I agree that my health and training data is processed to coach me. It is treated as sensitive data and I can export or delete it at any time.": ["Ik ga ermee akkoord dat mijn gezondheids- en trainingsgegevens worden verwerkt om mij te coachen. Ze worden als gevoelige gegevens behandeld en ik kan ze altijd exporteren of verwijderen.", "أوافق على معالجة بياناتي الصحية وبيانات تدريبي لتدريبي. تُعامل كبيانات حساسة ويمكنني تصديرها أو حذفها في أي وقت."],
  "I understand my coach is an AI, not a human and not a medical professional.": ["Ik begrijp dat mijn coach een AI is, geen mens en geen medisch professional.", "أفهم أن مدربي ذكاء اصطناعي، وليس إنسانًا ولا مختصًا طبيًا."],
  "I am 18 or older.": ["Ik ben 18 jaar of ouder.", "عمري 18 عامًا أو أكثر."],
  "Setting up…": ["Bezig met instellen…", "جارٍ الإعداد…"],
  "Create my coach": ["Maak mijn coach aan", "أنشئ مدربي"],
  "I already have an account": ["Ik heb al een account", "لدي حساب بالفعل"],
  "Welcome": ["Welkom", "أهلًا بك"],
  "Sign in, or join with the invite you were sent.": ["Log in, of doe mee met de uitnodiging die je hebt gekregen.", "سجّل الدخول، أو انضم عبر الدعوة التي وصلتك."],
  "Sign in with a passkey": ["Inloggen met een passkey", "تسجيل الدخول بمفتاح المرور"],
  "I have an invite code": ["Ik heb een uitnodigingscode", "لدي رمز دعوة"],
  "Code from another device": ["Code van een ander apparaat", "رمز من جهاز آخر"],
  "On a signed-in device, open Settings → Devices → Pair a new device. Lost every device? Ask your administrator for a recovery code.": ["Open op een ingelogd apparaat Instellingen → Apparaten → Nieuw apparaat koppelen. Al je apparaten kwijt? Vraag je beheerder om een herstelcode.", "على جهاز مسجّل الدخول، افتح الإعدادات ← الأجهزة ← إقران جهاز جديد. فقدت كل أجهزتك؟ اطلب رمز استرداد من المسؤول."],
  "Signing in…": ["Bezig met inloggen…", "جارٍ تسجيل الدخول…"],
  "Pair this device": ["Dit apparaat koppelen", "إقران هذا الجهاز"],
  "Use a code from another device": ["Gebruik een code van een ander apparaat", "استخدم رمزًا من جهاز آخر"],
  "Can't reach your coach": ["Je coach is niet bereikbaar", "تعذر الوصول إلى مدربك"],
  "The server did not answer. Check your connection.": ["De server reageerde niet. Controleer je verbinding.", "لم يستجب الخادم. تحقق من اتصالك."],
  "Starting call…": ["Gesprek starten…", "جارٍ بدء المكالمة…"],
  "Call ended": ["Gesprek beëindigd", "انتهت المكالمة"],
  "Call failed": ["Gesprek mislukt", "فشلت المكالمة"],
  "Listening to you…": ["Ik luister…", "أستمع إليك…"],
  "Speaking": ["Spreekt", "يتحدث"],
  "Thinking…": ["Denkt na…", "يفكر…"],
  "You're muted": ["Je microfoon staat uit", "الميكروفون مكتوم"],
  "Listening": ["Luistert", "يستمع"],
  "Minimize call": ["Gesprek minimaliseren", "تصغير المكالمة"],
  "Voice call": ["Spraakgesprek", "مكالمة صوتية"],
  "Call duration": ["Gespreksduur", "مدة المكالمة"],
  "Ends in": ["Eindigt over", "تنتهي خلال"],
  "You": ["Jij", "أنت"],
  "Hands-free is on": ["Handsfree staat aan", "وضع حر اليدين مفعّل"],
  "Release to send": ["Loslaten om te versturen", "اترك للإرسال"],
  "Hold to talk": ["Ingedrukt houden om te praten", "اضغط مطولًا للتحدث"],
  "Hands-free (detect when I stop talking)": ["Handsfree (merken wanneer ik stop met praten)", "حر اليدين (اكتشاف توقفي عن الكلام)"],
  "Mute": ["Dempen", "كتم"],
  "Unmute": ["Dempen opheffen", "إلغاء الكتم"],
  "Speaker": ["Luidspreker", "مكبر الصوت"],
  "End": ["Ophangen", "إنهاء"],
  "End call": ["Gesprek beëindigen", "إنهاء المكالمة"],
  "Call again": ["Opnieuw bellen", "اتصل مجددًا"],
  "Call in progress": ["Gesprek bezig", "مكالمة جارية"],
  "muted": ["gedempt", "مكتوم"],
  "Return": ["Terug", "عودة"],
  "Updated": ["Bijgewerkt", "تم التحديث"],
  "Message actions": ["Berichtacties", "إجراءات الرسالة"],
  "Copied": ["Gekopieerd", "تم النسخ"],
  "Start over with a fresh coach": ["Opnieuw beginnen met een nieuwe coach", "البدء من جديد بمدرب جديد"],
  "Clears your conversation, your coach's notes and plans, uploads and app screens, and starts again with today's defaults. Your account, sign-ins, settings and keys stay. Download your data first if you want a copy.": ["Wist je gesprek, de notities en plannen van je coach, uploads en app-schermen, en begint opnieuw met de huidige standaard. Je account, inlogmethodes, instellingen en sleutels blijven. Download eerst je gegevens als je een kopie wilt.", "يمسح محادثتك وملاحظات مدربك وخططه والملفات المرفوعة وشاشات التطبيق، ويبدأ من جديد بالإعدادات الافتراضية الحالية. يبقى حسابك وطرق تسجيل الدخول والإعدادات والمفاتيح. نزّل بياناتك أولًا إن أردت نسخة."],
  "Start over": ["Opnieuw beginnen", "ابدأ من جديد"],
  "Starting over…": ["Opnieuw beginnen…", "جارٍ البدء من جديد…"],
  "you": ["jij", "أنت"],
  "Suspended": ["Geschorst", "موقوف"],
  "Account suspended": ["Account geschorst", "الحساب موقوف"],
  "Suspend account": ["Account schorsen", "إيقاف الحساب"],
  "They are signed out and cannot sign in. Their coach is paused; nothing is deleted.": ["Ze zijn uitgelogd en kunnen niet inloggen. Hun coach staat stil; er wordt niets verwijderd.", "تم تسجيل خروجه ولا يمكنه تسجيل الدخول. مدربه متوقف مؤقتًا ولم يُحذف شيء."],
  "Signs them out everywhere and pauses their coach. Their data is kept and you can reactivate them at any time.": ["Logt ze overal uit en zet hun coach stil. Hun gegevens blijven bewaard en je kunt ze altijd weer activeren.", "يسجّل خروجه من كل الأجهزة ويوقف مدربه مؤقتًا. تبقى بياناته ويمكنك إعادة تفعيله في أي وقت."],
  "Reactivate": ["Weer activeren", "إعادة التفعيل"],
  "Suspend": ["Schorsen", "إيقاف"],
  "Permanently deletes their coach, workspace, uploads and history.": ["Verwijdert hun coach, werkruimte, uploads en geschiedenis definitief.", "يحذف مدربه ومساحة عمله وملفاته وسجله نهائيًا."],
  "Delete…": ["Verwijderen…", "حذف…"],
  "Delete permanently": ["Definitief verwijderen", "حذف نهائي"],
  "Deleting…": ["Verwijderen…", "جارٍ الحذف…"],
  "Open chat": ["Chat openen", "فتح الدردشة"],
  "Dictate": ["Dicteren", "إملاء"],
  "Dictate a message": ["Een bericht dicteren", "إملاء رسالة"],
  "Listening…": ["Aan het luisteren…", "جارٍ الاستماع…"],
  "Starting dictation…": ["Dicteren starten…", "جارٍ بدء الإملاء…"],
  "Finishing…": ["Afronden…", "جارٍ الإنهاء…"],
  "Cancel dictation": ["Dicteren annuleren", "إلغاء الإملاء"],
  "Done dictating": ["Klaar met dicteren", "انتهيت من الإملاء"],
  "Reconnect to dictate. You can keep typing while offline.": ["Maak opnieuw verbinding om te dicteren. Je kunt offline blijven typen.", "أعد الاتصال للإملاء. يمكنك متابعة الكتابة دون اتصال."],
  "Coach avatar": ["Coachavatar", "صورة المدرب"],
  "Reset avatar": ["Avatar herstellen", "إعادة ضبط الصورة"],
  "Let my coach change its name and avatar": ["Laat mijn coach de naam en avatar veranderen", "السماح لمدربي بتغيير اسمه وصورته"],
  "Optional. Ask in chat for a name or image; turn this off at any time.": ["Optioneel. Vraag in de chat om een naam of afbeelding; je kunt dit altijd uitschakelen.", "اختياري. اطلب اسمًا أو صورة في الدردشة؛ يمكنك إيقافه في أي وقت."],
  "Avatar generation uses a separate image service and counts toward your AI budget. Only the visual prompt is sent.": ["Avatars maken gebruikt een aparte afbeeldingsdienst en telt mee voor je AI-budget. Alleen de beeldbeschrijving wordt verstuurd.", "تستخدم الصور خدمة منفصلة وتُحتسب ضمن ميزانية الذكاء الاصطناعي. يُرسل وصف الصورة فقط."],
  "Image generation is not configured. Your coach can still change its name when allowed.": ["Afbeeldingen maken is niet ingesteld. Je coach kan wel de naam veranderen als je dit toestaat.", "إنشاء الصور غير مُعدّ. يمكن لمدربك تغيير اسمه إذا سمحت بذلك."],
  "Main": ["Hoofdnavigatie", "التنقل الرئيسي"],
  "Your coach": ["Je coach", "مدربك"],
  "Back to chat": ["Terug naar chat", "العودة إلى الدردشة"],
  "Skip to content": ["Naar inhoud", "انتقل إلى المحتوى"],
  "Dismiss": ["Sluiten", "إغلاق"],
  "Call": ["Bellen", "مكالمة"],
  "Connecting…": ["Verbinden…", "جارٍ الاتصال…"],
  "Reconnecting…": ["Opnieuw verbinden…", "جارٍ إعادة الاتصال…"],
  "View unavailable": ["Scherm niet beschikbaar", "الواجهة غير متاحة"],
  "You're offline. Showing saved data": ["Je bent offline. Opgeslagen gegevens worden getoond", "أنت غير متصل. تُعرض البيانات المحفوظة"],
  "Sending": ["Versturen", "جارٍ إرسال"],
  "queued item": ["item in de wachtrij", "عنصر في الانتظار"],
  "queued items": ["items in de wachtrij", "عناصر في الانتظار"],
  "Profile": ["Profiel", "الملف الشخصي"],
  "Your name": ["Je naam", "اسمك"],
  "Coach name": ["Naam van je coach", "اسم المدرب"],
  "Units": ["Eenheden", "الوحدات"],
  "Metric (km)": ["Metrisch (km)", "متري (كم)"],
  "Imperial (mi)": ["Imperiaal (mi)", "ميل"],
  "Time zone": ["Tijdzone", "المنطقة الزمنية"],
  "Quiet hours and your coach's schedule follow this.": ["Je stille uren en coachplanning gebruiken deze tijdzone.", "تعتمد ساعات الهدوء ومواعيد مدربك على هذه المنطقة الزمنية."],
  "Unknown time zone": ["Onbekende tijdzone", "منطقة زمنية غير معروفة"],
  "Appearance": ["Weergave", "المظهر"],
  "Theme": ["Thema", "السمة"],
  "Match my device": ["Volg mijn apparaat", "حسب الجهاز"],
  "Language": ["Taal", "اللغة"],
  "App and coach language": ["Taal van app en coach", "لغة التطبيق والمدرب"],
  "Your coach replies in this language. Saved across your devices.": ["Je coach antwoordt in deze taal. Opgeslagen voor al je apparaten.", "يرد مدربك بهذه اللغة. تُحفظ على جميع أجهزتك."],
  "Accent color": ["Accentkleur", "اللون المميز"],
  "Choose a color": ["Kies een kleur", "اختر لونًا"],
  "Saved across your devices. You can also ask your coach in chat.": ["Opgeslagen voor al je apparaten. Je kunt het ook in de chat aan je coach vragen.", "تُحفظ على جميع أجهزتك. يمكنك أيضًا طلب ذلك من مدربك في الدردشة."],
  "Your coach, your way": ["Je coach, op jouw manier", "مدربك، بطريقتك"],
  "Make OpenCoach feel like you. Changes save automatically.": ["Maak OpenCoach persoonlijk. Wijzigingen worden automatisch opgeslagen.", "اجعل OpenCoach يناسبك. تُحفظ التغييرات تلقائيًا."],
  "Personalize": ["Personaliseren", "التخصيص"],
  "Coaching": ["Coaching", "التدريب"],
  "Account & data": ["Account en gegevens", "الحساب والبيانات"],
  "Saving…": ["Opslaan…", "جارٍ الحفظ…"],
  "Saved": ["Opgeslagen", "تم الحفظ"],
  "Could not save": ["Opslaan mislukt", "تعذر الحفظ"],
  "Notifications": ["Meldingen", "الإشعارات"],
  "Your limits. Your coach cannot change them: messages are held during quiet hours and capped by these budgets.": ["Jij bepaalt deze grenzen. Je coach kan ze niet wijzigen: berichten wachten tijdens stille uren en blijven binnen deze limieten.", "أنت تحدد هذه الحدود ولا يستطيع المدرب تغييرها. تُؤجَّل الرسائل خلال ساعات الهدوء وتخضع لهذه الحدود."],
  "Quiet hours": ["Stille uren", "ساعات الهدوء"],
  "Messages written during this window wait until it ends.": ["Berichten wachten tot de stille uren voorbij zijn.", "تنتظر الرسائل المكتوبة خلال هذه الفترة حتى تنتهي."],
  "From": ["Van", "من"],
  "Until": ["Tot", "إلى"],
  "Maximum proactive messages per day": ["Maximum aantal coachberichten per dag", "الحد الأقصى لرسائل المدرب الاستباقية يوميًا"],
  "Only messages your coach starts count. This is a ceiling, not a target. 0 means replies only.": ["Alleen berichten die je coach zelf begint tellen mee. Dit is een bovengrens, geen doel. Bij 0 krijg je alleen antwoorden.", "تُحسب فقط الرسائل التي يبدأها مدربك. هذا حد أقصى، وليس هدفًا. القيمة 0 تعني الردود فقط."],
  "Maximum proactive messages per week": ["Maximum aantal coachberichten per week", "الحد الأقصى لرسائل المدرب الاستباقية أسبوعيًا"],
  "Across the last 7 days. Your coach decides when a message is useful, within both limits.": ["Over de afgelopen 7 dagen. Je coach bepaalt wanneer een bericht nuttig is, binnen beide grenzen.", "خلال آخر 7 أيام. يقرر مدربك متى تكون الرسالة مفيدة، ضمن كلا الحدين."],
  "Minimum gap between them": ["Minimale tijd ertussen", "أقل فترة بين الرسائل"],
  "No minimum": ["Geen minimum", "بلا حد أدنى"],
  "Pause until": ["Pauzeren tot", "الإيقاف حتى"],
  "Vacation mode: your coach stays quiet until this date.": ["Vakantiemodus: je coach blijft stil tot deze datum.", "وضع الإجازة: لا يبادر مدربك بالرسائل حتى هذا التاريخ."],
  "Resume now": ["Nu hervatten", "استئناف الآن"],
  "Push notifications": ["Pushmeldingen", "الإشعارات الفورية"],
  "This browser does not support push notifications.": ["Deze browser ondersteunt geen pushmeldingen.", "هذا المتصفح لا يدعم الإشعارات الفورية."],
  "On iPhone and iPad, add OpenCoach to your Home Screen first.": ["Voeg OpenCoach op iPhone en iPad eerst toe aan je beginscherm.", "على iPhone وiPad، أضف OpenCoach إلى الشاشة الرئيسية أولًا."],
  "Blocked in your browser settings.": ["Geblokkeerd in je browserinstellingen.", "محظورة في إعدادات المتصفح."],
  "On this device.": ["Op dit apparaat.", "على هذا الجهاز."],
  "Voice": ["Spraak", "الصوت"],
  "Call mode": ["Gespreksmodus", "وضع المكالمات"],
  "Realtime is the most natural. Cascaded works with any model and keeps audio processing on the server.": ["Realtime klinkt het natuurlijkst. Cascaded werkt met elk model en verwerkt audio op de server.", "المحادثة الفورية هي الأكثر طبيعية. الوضع المتتابع يعمل مع أي نموذج ويعالج الصوت على الخادم."],
  "Calls are not available on this server.": ["Bellen is niet beschikbaar op deze server.", "المكالمات غير متاحة على هذا الخادم."],
  "Realtime": ["Realtime", "فوري"],
  "Realtime (unavailable)": ["Realtime (niet beschikbaar)", "فوري (غير متاح)"],
  "Cascaded": ["Cascaded", "متتابع"],
  "Cascaded (unavailable)": ["Cascaded (niet beschikbaar)", "متتابع (غير متاح)"],
  "Coach voice": ["Stem van je coach", "صوت المدرب"],
  "Reply with voice notes": ["Antwoord met spraakberichten", "الرد برسائل صوتية"],
  "Never": ["Nooit", "أبدًا"],
  "When I send one": ["Als ik er een stuur", "عندما أرسل رسالة صوتية"],
  "Always": ["Altijd", "دائمًا"],
  "Privacy": ["Privacy", "الخصوصية"],
  "Keep photo location": ["Fotolocatie bewaren", "الاحتفاظ بموقع الصور"],
  "Off: GPS data is removed from photos before your coach sees them.": ["Uit: gps-gegevens worden uit foto's verwijderd voordat je coach ze ziet.", "عند الإيقاف، تُحذف بيانات الموقع من الصور قبل أن يراها مدربك."],
  "Share feedback with developers": ["Feedback delen met ontwikkelaars", "مشاركة الملاحظات مع المطورين"],
  "Off by default. Lets your coach's notes about the app reach its developers.": ["Standaard uit. Deel appfeedback van je coach met de ontwikkelaars.", "متوقف افتراضيًا. يسمح بوصول ملاحظات مدربك عن التطبيق إلى المطورين."],
  "Spending limits": ["Bestedingslimieten", "حدود الإنفاق"],
  "Caps on what your coach may spend on AI each day and month. When a limit is reached your coach pauses.": ["Begrens dagelijks en maandelijks AI-gebruik. Je coach pauzeert zodra de limiet is bereikt.", "حدد إنفاق مدربك على الذكاء الاصطناعي يوميًا وشهريًا. يتوقف المدرب عند بلوغ الحد."],
  "Daily limit": ["Daglimiet", "الحد اليومي"],
  "Monthly limit": ["Maandlimiet", "الحد الشهري"],
  "Devices": ["Apparaten", "الأجهزة"],
  "Sign in on another phone or computer with a one-time code, or add a passkey to this device.": ["Log in op een ander apparaat met een eenmalige code, of voeg hier een passkey toe.", "سجل الدخول على جهاز آخر برمز لمرة واحدة، أو أضف مفتاح مرور لهذا الجهاز."],
  "Pair a new device": ["Nieuw apparaat koppelen", "ربط جهاز جديد"],
  "Copy": ["Kopiëren", "نسخ"],
  "Expires in": ["Verloopt over", "تنتهي صلاحيته خلال"],
  "Enter it on the new device's sign-in screen.": ["Voer hem in op het inlogscherm van het nieuwe apparaat.", "أدخله في شاشة تسجيل الدخول على الجهاز الجديد."],
  "Add a passkey": ["Passkey toevoegen", "إضافة مفتاح مرور"],
  "Passkey added": ["Passkey toegevoegd", "تمت إضافة مفتاح المرور"],
  "Subscribe in Google, Apple or Outlook calendar to see your coach's plan. Anyone with the link can see your schedule, so keep it private.": ["Abonneer je in Google, Apple of Outlook om je plan te zien. Iedereen met de link kan je schema zien: houd de link privé.", "اشترك عبر تقويم Google أو Apple أو Outlook لعرض خطتك. يستطيع أي شخص لديه الرابط رؤية جدولك، لذا حافظ على خصوصيته."],
  "Show subscribe link": ["Abonnementslink tonen", "عرض رابط الاشتراك"],
  "Calendar subscribe URL": ["Kalenderabonnementslink", "رابط الاشتراك بالتقويم"],
  "Copy link": ["Link kopiëren", "نسخ الرابط"],
  "Link copied": ["Link gekopieerd", "تم نسخ الرابط"],
  "Select the link and copy it": ["Selecteer de link en kopieer hem", "حدد الرابط وانسخه"],
  "About": ["Over", "حول"],
  "Account": ["Account", "الحساب"],
  "Features": ["Functies", "الميزات"],
  "Demo mode.": ["Demomodus.", "وضع العرض التجريبي."],
  "This server runs a scripted demo coach without an AI model. Replies are pre-written and nothing you say is analysed.": ["Deze server gebruikt een demo zonder AI-model. Antwoorden zijn vooraf geschreven; je berichten worden niet geanalyseerd.", "يعمل هذا الخادم بمدرب تجريبي دون نموذج ذكاء اصطناعي. الردود مكتوبة مسبقًا ولا تُحلل رسائلك."],
  "Your coach is an AI. It is not a doctor and cannot diagnose. If something feels wrong, stop and see a professional.": ["Je coach is AI, geen arts, en kan geen diagnose stellen. Stop bij klachten en raadpleeg een professional.", "مدربك ذكاء اصطناعي، وليس طبيبًا ولا يمكنه التشخيص. إذا شعرت بمشكلة، توقف واستشر مختصًا."],
  "Sign out of this device": ["Uitloggen op dit apparaat", "تسجيل الخروج من هذا الجهاز"],
  "Your data": ["Je gegevens", "بياناتك"],
  "Delete account": ["Account verwijderen", "حذف الحساب"],
  "Message": ["Bericht", "رسالة"],
  "Message composer": ["Berichtvenster", "منطقة كتابة الرسالة"],
  "Your message will send when you’re back online.": ["Je bericht wordt verstuurd zodra je weer online bent.", "ستُرسل رسالتك عند عودتك إلى الاتصال."],
  "Message your coach…": ["Stuur je coach een bericht…", "اكتب لمدربك…"],
  "Attach": ["Bijvoegen", "إرفاق"],
  "Attachments to send": ["Bijlagen om te versturen", "مرفقات للإرسال"],
  "Add photos or files": ["Foto's of bestanden toevoegen", "إضافة صور أو ملفات"],
  "Add an attachment": ["Bijlage toevoegen", "إضافة مرفق"],
  "Photos & files": ["Foto's en bestanden", "صور وملفات"],
  "Take a photo": ["Foto maken", "التقاط صورة"],
  "Enter to send": ["Enter om te versturen", "Enter للإرسال"],
  "Shift + Enter for a new line": ["Shift + Enter voor een nieuwe regel", "Shift + Enter لسطر جديد"],
  "Record a voice note": ["Spraakbericht opnemen", "تسجيل رسالة صوتية"],
  "Voice notes aren’t configured": ["Spraakberichten zijn niet ingesteld", "الرسائل الصوتية غير مهيأة"],
  "Voice notes aren’t set up on this server yet. You can still dictate using the microphone on your keyboard.": ["Spraakberichten zijn nog niet ingesteld. Je kunt de microfoon van je toetsenbord gebruiken.", "الرسائل الصوتية غير مهيأة على هذا الخادم. يمكنك استخدام ميكروفون لوحة المفاتيح للإملاء."],
  "Reconnect to record a voice note. You can keep typing while offline.": ["Maak opnieuw verbinding om een spraakbericht op te nemen. Typen kan offline gewoon doorgaan.", "أعد الاتصال لتسجيل رسالة صوتية. يمكنك متابعة الكتابة دون اتصال."],
  "Send message": ["Bericht versturen", "إرسال الرسالة"],
  "Dismiss message": ["Melding sluiten", "إغلاق التنبيه"],
  "Listen before sending": ["Luister voor het versturen", "استمع قبل الإرسال"],
  "Recording…": ["Opnemen…", "جارٍ التسجيل…"],
  "Starting microphone…": ["Microfoon starten…", "جارٍ تشغيل الميكروفون…"],
  "Preparing preview…": ["Voorbeeld voorbereiden…", "جارٍ تجهيز المعاينة…"],
  "Stop recording": ["Opname stoppen", "إيقاف التسجيل"],
  "Send voice note": ["Spraakbericht versturen", "إرسال الرسالة الصوتية"],
  "Reconnect to send. Your recording is kept here.": ["Maak opnieuw verbinding om te versturen. Je opname blijft hier bewaard.", "أعد الاتصال للإرسال. تسجيلك محفوظ هنا."],
  "Try again": ["Opnieuw proberen", "حاول مجددًا"],
  "Close": ["Sluiten", "إغلاق"],
  "Open": ["Openen", "فتح"],
  "Close image": ["Afbeelding sluiten", "إغلاق الصورة"],
  "Unavailable": ["Niet beschikbaar", "غير متاح"],
  "Voice note": ["Spraakbericht", "رسالة صوتية"],
  "Rest": ["Rust", "راحة"],
  "Recovery": ["Herstel", "تعافٍ"],
  "Partial": ["Deels", "جزئي"],
  "What your coach changed": ["Wat je coach heeft gewijzigd", "ما غيره مدربك"],
  "Saved updates to your coach's files and screens, newest first.": ["Opgeslagen wijzigingen aan de bestanden en schermen van je coach, nieuwste eerst.", "تحديثات محفوظة لملفات مدربك وواجهاته، من الأحدث إلى الأقدم."],
  "Your coach was set up": ["Je coach is ingesteld", "تم إعداد مدربك"],
  "Earlier screen restored": ["Eerdere schermversie hersteld", "تمت استعادة إصدار سابق للواجهة"],
  "Screens published": ["Schermen gepubliceerd", "تم نشر الواجهات"],
  "Workspace edited outside the coach": ["Werkruimte buiten de coach om gewijzigd", "تم تعديل مساحة العمل من خارج المدرب"],
  "Training data backed up": ["Back-up van trainingsgegevens gemaakt", "تم حفظ نسخة احتياطية من بيانات التدريب"],
  "Coach saved changes": ["Je coach heeft wijzigingen opgeslagen", "حفظ مدربك تغييرات"],
  "Screen files": ["Schermbestanden", "ملفات الواجهات"],
  "Training data": ["Trainingsgegevens", "بيانات التدريب"],
  "Coach notes": ["Coachnotities", "ملاحظات المدرب"],
  "Plan files": ["Planbestanden", "ملفات الخطة"],
  "Research": ["Onderzoek", "أبحاث"],
  "Calendar export": ["Agenda-export", "تصدير التقويم"],
  "Coach workspace": ["Werkruimte van je coach", "مساحة عمل المدرب"],
  "Technical details": ["Technische details", "تفاصيل تقنية"],
  "Local Git revision": ["Lokale Git-versie", "إصدار Git محلي"],
  "Hide changes": ["Wijzigingen verbergen", "إخفاء التغييرات"],
  "Show changes": ["Wijzigingen tonen", "عرض التغييرات"],
  "Nothing yet.": ["Nog niets.", "لا شيء بعد."],
  "Screen history": ["Schermgeschiedenis", "سجل الواجهات"],
  "Don't like a change to one of your screens? Go back to an earlier version.": ["Niet tevreden over een wijziging? Herstel een eerdere schermversie.", "لا يعجبك تغيير في إحدى الواجهات؟ عد إلى إصدار سابق."],
  "Your coach hasn't published any screens yet.": ["Je coach heeft nog geen schermen gepubliceerd.", "لم ينشر مدربك أي واجهات بعد."],
  "No earlier versions.": ["Geen eerdere versies.", "لا إصدارات سابقة."],
  "Version": ["Versie", "الإصدار"],
  "version": ["versie", "الإصدار"],
  "No summary": ["Geen samenvatting", "لا ملخص"],
  "Revert to this": ["Deze herstellen", "استعادة هذا الإصدار"],
  "Take your coach with you: your workspace, uploads, message history and settings in one bundle.": ["Neem alles mee: je coachgegevens, uploads, gesprekken en instellingen in één bestand.", "خذ بياناتك معك: ملفاتك ومرفقاتك وسجل المحادثات والإعدادات في حزمة واحدة."],
  "Export everything": ["Alles exporteren", "تصدير الكل"],
  "Preparing export": ["Export voorbereiden", "إعداد التصدير"],
  "Preparing your export. This can take a minute.": ["Je export wordt voorbereid. Dit kan even duren.", "جارٍ إعداد التصدير. قد يستغرق دقيقة."],
  "Your export is ready.": ["Je export is klaar.", "تصديرك جاهز."],
  "Download": ["Downloaden", "تنزيل"],
  "Permanently deletes your coach, workspace, uploads and history. Backups are removed within 30 days. This cannot be undone.": ["Verwijdert je coach, gegevens, uploads en geschiedenis permanent. Back-ups verdwijnen binnen 30 dagen. Dit kan niet ongedaan worden gemaakt.", "يحذف مدربك وملفاتك ومرفقاتك وسجلك نهائيًا. تُحذف النسخ الاحتياطية خلال 30 يومًا. لا يمكن التراجع."],
  "Type": ["Typ", "اكتب"],
  "to confirm": ["om te bevestigen", "للتأكيد"],
  "Delete my account and data": ["Mijn account en gegevens verwijderen", "حذف حسابي وبياناتي"],
  "Health Connect": ["Health Connect", "Health Connect"],
  "Import workouts from this device. Android will ask for permission, and imported workouts are sent to your coach.": ["Importeer trainingen van dit apparaat. Android vraagt toestemming; je coach ontvangt de trainingen.", "استورد التمارين من هذا الجهاز. سيطلب Android إذنك وتُرسل التمارين المستوردة لمدربك."],
  "Import period": ["Importperiode", "فترة الاستيراد"],
  "Last": ["Laatste", "آخر"],
  "days": ["dagen", "أيام"],
  "Importing workouts…": ["Trainingen importeren…", "جارٍ استيراد التمارين…"],
  "Import workouts": ["Trainingen importeren", "استيراد التمارين"],
  "Nothing to show.": ["Niets om te tonen.", "لا شيء للعرض."],
  "Cost per day": ["Kosten per dag", "التكلفة يوميًا"],
  "Trace": ["Logboek", "السجل"],
  "Turn": ["Beurt", "الجولة"],
  "Create invite code": ["Uitnodigingscode maken", "إنشاء رمز دعوة"],
  "Admin": ["Beheer", "الإدارة"],
  "Athletes": ["Atleten", "الرياضيون"],
  "Invite someone": ["Iemand uitnodigen", "دعوة شخص"],
  "Costs by day": ["Kosten per dag", "التكاليف يوميًا"],
  "Recent turns": ["Recente beurten", "الجولات الأخيرة"],
  "minutes": ["minuten", "دقائق"],
  "hours": ["uur", "ساعات"],
  "Photo": ["Foto", "صورة"],
  "Audio": ["Audio", "صوت"],
  "Hide transcript": ["Transcript verbergen", "إخفاء النص"],
  "Transcript": ["Transcript", "النص"],
  "Uploading": ["Uploaden", "جارٍ الرفع"],
  "Sending…": ["Versturen…", "جارٍ الإرسال…"],
  "Waiting for connection. It will send automatically.": ["Wacht op verbinding. Wordt automatisch verstuurd.", "بانتظار الاتصال. ستُرسل تلقائيًا."],
  "Not sent": ["Niet verstuurd", "لم تُرسل"],
  "Discard": ["Verwijderen", "تجاهل"],
  "This card is no longer available.": ["Deze kaart is niet meer beschikbaar.", "هذه البطاقة لم تعد متاحة."],
  "Voice reply": ["Spraakantwoord", "رد صوتي"],
  "Message options": ["Berichtopties", "خيارات الرسالة"],
  "Helpful": ["Nuttig", "مفيد"],
  "Not helpful": ["Niet nuttig", "غير مفيد"],
  "Copy text": ["Tekst kopiëren", "نسخ النص"],
  "Coach is writing": ["Je coach schrijft", "المدرب يكتب"],
  "Conversation": ["Gesprek", "المحادثة"],
  "Loading messages": ["Berichten laden", "جارٍ تحميل الرسائل"],
  "Say hello to your coach.": ["Begroet je coach.", "رحب بمدربك."],
  "Tell them what you're training for, your goals, or just how today went.": ["Vertel waarvoor je traint, wat je doelen zijn of hoe je dag was.", "أخبره بما تتدرب له أو بأهدافك أو كيف كان يومك."],
  "Show earlier messages": ["Eerdere berichten tonen", "عرض الرسائل السابقة"],
  "New messages": ["Nieuwe berichten", "رسائل جديدة"],
  "Safety notice": ["Veiligheidsmelding", "تنبيه السلامة"],
  "This may be urgent": ["Dit kan dringend zijn", "قد يكون هذا عاجلًا"],
  "Please look after yourself first": ["Zorg eerst voor jezelf", "اعتنِ بنفسك أولًا"],
  "Dismiss for now": ["Voorlopig sluiten", "إغلاق مؤقتًا"],
  "Updated by your coach": ["Bijgewerkt door je coach", "حدّثه مدربك"],
  "Offline: showing what was last saved.": ["Offline: laatst opgeslagen versie.", "دون اتصال: يُعرض آخر ما حُفظ."],
  "isn't available right now.": ["is nu niet beschikbaar.", "غير متاح الآن."],
  "If this is an emergency, or you have chest pain, trouble breathing, fainting, confusion or severe pain, stop exercising and call your local emergency number now (for example 112, 911 or 999).": ["Bij een noodgeval, pijn op de borst, ademnood, flauwvallen, verwardheid of ernstige pijn: stop met sporten en bel nu het lokale alarmnummer (bijvoorbeeld 112, 911 of 999).", "إذا كانت هذه حالة طارئة، أو لديك ألم في الصدر أو صعوبة تنفس أو إغماء أو ارتباك أو ألم شديد، توقف عن التمرين واتصل برقم الطوارئ المحلي الآن (مثل 112 أو 911 أو 999)."],
  "Chest pain or pressure, palpitations or fainting need medical attention. Stop training until a clinician has seen you.": ["Pijn of druk op de borst, hartkloppingen of flauwvallen vragen medische aandacht. Stop met trainen totdat een zorgverlener je heeft onderzocht.", "ألم الصدر أو الضغط عليه أو الخفقان أو الإغماء يحتاج إلى رعاية طبية. توقف عن التدريب حتى يفحصك مختص."],
  "Confusion, vomiting or stopping sweating in the heat can be heat illness. Get out of the heat, cool down and seek urgent medical help.": ["Verwardheid, braken of niet meer zweten in de hitte kunnen op hitteziekte wijzen. Zoek een koele plek, koel af en zoek dringend medische hulp.", "الارتباك أو القيء أو توقف التعرق في الحر قد يدل على مرض مرتبط بالحرارة. ابتعد عن الحر، وبرّد جسمك، واطلب مساعدة طبية عاجلة."],
  "Sharp bone pain, or pain at rest or at night, can mean a stress injury. Stop the activity that hurts and have it checked.": ["Scherpe botpijn of pijn in rust of 's nachts kan op een stressblessure wijzen. Stop met de activiteit die pijn doet en laat het onderzoeken.", "ألم العظام الحاد أو الألم أثناء الراحة أو ليلًا قد يدل على إصابة إجهادية. توقف عن النشاط المؤلم وافحصه طبيًا."],
  "Numbness, weakness, a head injury, or back pain with groin numbness or bladder changes needs urgent medical assessment.": ["Gevoelloosheid, krachtverlies, hoofdletsel, of rugpijn met een doof gevoel in de lies of veranderingen bij plassen heeft dringend medisch onderzoek nodig.", "الخدر أو الضعف أو إصابة الرأس، أو ألم الظهر مع خدر في منطقة الفخذين الداخلية أو تغيّر في التحكم بالمثانة، يحتاج إلى تقييم طبي عاجل."],
  "Dark urine and severe muscle pain after hard exercise need urgent medical care.": ["Donkere urine en ernstige spierpijn na zware inspanning vragen dringende medische zorg.", "البول الداكن والألم العضلي الشديد بعد تمرين شاق يحتاجان إلى رعاية طبية عاجلة."],
  "A swollen, painful calf after travel or rest can be a clot. Seek medical care promptly.": ["Een gezwollen, pijnlijke kuit na reizen of rust kan op een bloedstolsel wijzen. Zoek snel medische zorg.", "قد يشير تورم ربلة الساق وألمها بعد السفر أو الراحة إلى جلطة. اطلب رعاية طبية سريعًا."],
  "If food, weight or exercise feels out of control, talking to a doctor or an eating-disorder helpline can help. You deserve support.": ["Als eten, gewicht of sport onbeheersbaar voelt, kan een arts of hulplijn voor eetstoornissen helpen. Je verdient steun.", "إذا شعرت أن الأكل أو الوزن أو التمرين خارج سيطرتك، فقد يساعدك التحدث إلى طبيب أو خط دعم لاضطرابات الأكل. أنت تستحق الدعم."],
  "If you are thinking about harming yourself, please contact your local emergency number or a crisis line in your country right now. You are not alone.": ["Denk je eraan jezelf iets aan te doen? Bel nu het lokale alarmnummer of een crisislijn in je land. Je staat er niet alleen voor.", "إذا كنت تفكر في إيذاء نفسك، اتصل برقم الطوارئ المحلي أو خط الأزمات في بلدك الآن. لست وحدك."],
  "This may need medical attention. If you are unsure, contact a clinician or your local emergency number.": ["Dit kan medische aandacht vereisen. Neem bij twijfel contact op met een zorgverlener of het lokale alarmnummer.", "قد يحتاج هذا إلى رعاية طبية. إذا كنت غير متأكد، اتصل بمختص أو برقم الطوارئ المحلي."]
};
