/**
 * Languages offered in the picker, each named in itself. The app's own labels come from curated tables (English,
 * Dutch, Arabic) or are generated by the server on first use; the coach writes in any language regardless.
 */
export const LANGUAGES = [
  'en', 'en-GB', 'nl', 'ar', 'de', 'fr', 'es', 'es-419', 'it', 'pt-PT', 'pt-BR', 'ca', 'eu', 'gl', 'ga', 'cy', 'is', 'nb', 'sv', 'da', 'fi', 'et', 'lv', 'lt',
  'pl', 'cs', 'sk', 'sl', 'hr', 'sr', 'bs', 'hu', 'ro', 'bg', 'mk', 'sq', 'el', 'tr', 'uk', 'ru', 'be', 'ka', 'hy', 'az', 'kk', 'uz',
  'he', 'fa', 'ur', 'ps', 'ku', 'hi', 'bn', 'pa', 'gu', 'mr', 'ta', 'te', 'kn', 'ml', 'si', 'ne', 'zh-CN', 'zh-TW', 'ja', 'ko', 'mn',
  'vi', 'th', 'lo', 'km', 'my', 'id', 'ms', 'fil', 'sw', 'am', 'so', 'ha', 'yo', 'ig', 'zu', 'xh', 'af',
];

export function languageName(code: string): string {
  try {
    return new Intl.DisplayNames([code], { type: 'language' }).of(code) ?? code;
  } catch {
    return code;
  }
}

export function languageOptions(current: string): Array<{ value: string; label: string }> {
  const codes = LANGUAGES.includes(current) ? LANGUAGES : [...LANGUAGES, current];
  return codes
    .map((code) => ({ value: code, label: languageName(code).replace(/^\p{Ll}/u, (c) => c.toLocaleUpperCase(code)) }))
    .sort((a, b) => a.label.localeCompare(b.label));
}
